name: Fetch Tomorrow.io Forecast

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Fetching the weather forecast from Tomorrow.io
        run: |
          FILE=./src/json/forecast.json
          echo "Fetching today's forecast from Tomorrow.io..."
          response=$(curl --request POST \
            --url 'https://api.tomorrow.io/v4/timelines?apikey=${{ secrets.CLIMACELL_API_KEY }}' \
            --compressed \
            --header 'Accept-Encoding: gzip' \
            --header 'accept: application/json' \
            --header 'content-type: application/json' \
            --data '
            {
              "location": "19380",
              "fields": [
                "temperature,dewPoint"
              ],
              "units": "imperial",
              "timesteps": [
                "string"
              ],
              "startTime": "now",
              "endTime": "nowPlus6h",
              "timezone": "string"
            }
            ')
          status=$?
          if [ $status -eq 0 ]; then
              echo $response > $FILE
              echo "$FILE saved."
          else
              echo "curl exit code: ($status) $response"
              exit $status
          fi
      - name: Committing changes to git
        env:
          GIT_OWNER_EMAIL: ${{ secrets.GIT_OWNER_EMAIL }} 
          PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config user.email "$GIT_OWNER_EMAIL"
          git config user.name "tikaro"
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -a -m "Update forecast data from Climacell API"
            git remote rm origin
            git remote add origin https://tikaro:$PUSH_TOKEN@github.com/tikaro/sandex.git
            git push origin HEAD:main
          else
            echo 'unable to detect any changes'
          fi
