# This is a basic workflow to help you get started with Actions

name: fetch-climacell

# Controls when the action will run. 
on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  call-climacell-api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: save API
      run:  curl --location --request GET 'https://data.climacell.co/v4/timelines?apikey=isddI3J554xIy57ZycsDOI2hkRCINvdM&timesteps=1h&location=39.99,-75.58&fields=temperature,humidity,dewPoint&units=imperial' > response.json
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: response.json
